- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
The `rotation` field of most elements on most endpoints currently show a non-degree non-radian number between 89 and 91 with inconsistent steps between angles. This change should restore the intended behaviour: a value with 0 as north, 90 as east, etc.
> Expose correct rotation values

- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Player.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Library.h
i moved the loop to group the inventory items and build the json to two extra methods
every time where the inventory will be returned in the api is an own for loop with the same stuff, that is now moved to methods
and it would be easier to improve these functions or extend something, without change it everywhere
i don't know if i do everything right, it's one of my first c++ code, so please check if thats correct/good
getDoggo was the first place where i tested the methods, and it seems to work 🎉
if everything is fine i would replace it for everything else
just for your information:
i changed `UKismetSystemLibrary::GetClassDisplayName(ClassName->GetClass()))` to `UKismetSystemLibrary::GetClassDisplayName(Item.Key))` because the `ClassName->getClass()` always returned …
> refactor: move group inventory to additional method

- Source/FicsitRemoteMonitoring/Private/FRM_Drones.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Power.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Vehicles.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Library.h
i refactored the inventory stuff to the GetGroupedInventoryItems & GetInventoryJSON methods
- getDrones: add missing FuelInventory
- getTruckStation: renamed Storage to FuelInventory and it returns now the Fuel Inventory (more consistent to other endpoints)
- getVehicles: renamed Storage to Inventory and Fuel to FuelInventory (more consistent to other endpoints)
i tested everything and it looks good, but please check it again
i don't touched the getSpaceElevator endpoint because i think you are working on it for #91?
> refactor: refactor all inventory jsons to GetGroupedInventoryItems and GetInventoryJSON

- Source/FicsitRemoteMonitoring/Private/FRM_Drones.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Vehicles.cpp
- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Factory.h
- Source/FicsitRemoteMonitoring/Public/FRM_Library.h
- Source/FicsitRemoteMonitoring/Public/FicsitRemoteMonitoring.h
Normalize PowerInfo object for many buildings, that contains:
`CircuitID`
`CircuitGroupID`
`PowerConsumed`
Also adds a `/getResourceSinkBuilding` endpoint that gives `location` and `PowerInfo` for all sinks.
This also removes random redundant `CircuitID` references on many of the objects.
Closes #98
> FEATURE: normalize power info. Add /getResourceSinkBuilding

- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
Adds PowerInfo metrics for trains
Check for valid power info before parsing. Return default nil powerinfo if it cannot be found.
> Add train power info

- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
- Source/FicsitRemoteMonitoring/Public/FicsitRemoteMonitoring.h
it's a fix for #117 🎉
only took 14 hours to find that out 😄
the uWS server does not close correctly, causing the first WebSocket server to continue listening for requests and leading to game crashes due to a null AFicsitRemoteMonitoring object
i now call `us_listen_socket_close` to prevent new connections and close all connected WebSocket clients in StopWebSocketServer to terminate the uWS loop completley
Adding the 'Connection: close' header prevents keep-alive after an HTTP request
uWebSockets can't close these connections, the client must close them, with 'Connection: close,' the connection will close automatically after the response is sent
> fix: StopWebSocketServer will now close the websocket completely #117

- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Factory.h
- Source/FicsitRemoteMonitoring/Public/FicsitRemoteMonitoring.h
Adds `/getSessionInfo` to get current session name.
Returns `{"SessionName":"the current game session name"}`
Closes #100
> add session info endpoint

- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
The compiler UE uses for Windows appears to generate code that allows this, whereas clang doesn't.
> Fix #126 - Avoid null dereference on Linux

- Source/FicsitRemoteMonitoring/Private/FRM_Drones.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Power.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Drones.h
- Source/FicsitRemoteMonitoring/Public/FRM_Library.h
* Add max power consumed stat to power metrics
* Normalize train power. All train platforms report their power info stat.
* Station no longer aggregates all power inside it, simplifying some math.
* Add drone names for drones (closes #123 )
> Normalize train power. Add drone port names.

- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
another fix 😄
it prevents crashing the http server/game if an invalid icon is opened
before: http://localhost:8080/Icons/Desc_Screw_C.png crashes the game
after: 404 will be returned, no crash
> fix: prevent crashing http server on invalid icon file

- Source/FicsitRemoteMonitoring/Private/FRM_Drones.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Player.cpp
Feel like this is less brittle to use the actual classes in GetAllActorsOfClass where possible. These are the ones I can find that can be replaced.
> reduce reliance on LoadObject

- Source/FicsitRemoteMonitoring/Private/FRM_Drones.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Player.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Production.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Vehicles.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_World.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Library.h
i added FRM_Library::CreateBaseJsonObject to create a base `MakeShared<FJsonObject>();` object with the ID field and added it to many endpoints
i use GetName as unique id (e.g. Build_SpaceElevator_C_2147393189) it seems that this is an unique id for the savegame.
GetUniqueID has each time the savegame will be reloaded (it's the UObject id of the current game)
if we want to change this, we can do that in CreateBaseJsonObject without changing it everywhere
i replaced the Index ID (0, 1, 2, ...) in drone, doggo and power slug endpoint
it's easier to work with the response of the api with an unique ID
> feat: add ID fields to many endpoints

- Source/FicsitRemoteMonitoring/Private/FRM_Power.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Request.cpp
- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
- Source/FicsitRemoteMonitoring/Public/FRM_Power.h
- Source/FicsitRemoteMonitoring/Public/FRM_Request.h
- Source/FicsitRemoteMonitoring/Public/FRM_RequestData.h
- Source/FicsitRemoteMonitoring/Public/FicsitRemoteMonitoring.h
- support for POST requests, it accepts an array of objects or an object, the FRequestData.Body is always an array, so we don't need to check this manually in any endpoint and can execute multiple actions with one request
- Name in getSwitches is now the name of the power switch itself
- added Priority to getSwitches (-1 for power switch 0 - 8 for priority power switches)
example for a setSwitches request (curl):
```
curl --location 'http://localhost:8081/setSwitches' \
--header 'Content-Type: application/json' \
--data '{
"ID": "Build_PriorityPowerSwitch_C_2147413991",
"name": "hello",
"status": false,
"priority": 0
}'
```
every field is optional, only name, status OR priority is required to do an update in setSwitches
if you try to update multiple switches you could get an array with …
> feat: add support for post requests and add setSwitches to update name, priority or status

- Source/FicsitRemoteMonitoring/Private/FRM_Library.cpp
- Source/FicsitRemoteMonitoring/Private/FRM_Power.cpp
- MaxAmount (stacksize) for items
- FuelInventory to getGenerators (e.g. biomass for a biomass burner or water & coal in a coal generator)
> feat: add stack size for items and fuel inventory to generators

- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
more fields for /getSessionInfo
- Hours, Minutes, Seconds = current game time
- DayLength = length of the day in minutes
- NightLength = length of the night in minutes
- PassedDays = passed days in this save
- NumberOfDaysSinceLastDeath = days since last incident
- IsDay = obviously true for day, false for night
- TotalPlayDuration = play time in seconds
- TotalPlayDurationText = formatted play time (142:20:33)
> feat: add more fields to /getSessionInfo

- Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp
There were many places where the code could dereference a NULL or invalid pointer, and the inner loop's flow was also quite complex. Ensure pointers are valid before using them. Refactor the inner loop into a for-loop to make it easier to prove that the pointers are valid, and also deduplicate the code paths in the process.
The JSON output should be unchanged for empty and cargo train station platforms. Other kinds of train stations are now handled as if they were empty platforms.
> FRM_Trains.cpp: Fix NULL pointer deref in getTrainStation

- Source/FicsitRemoteMonitoring/Private/FRM_Power.cpp
The `GetAvailableFuelClasses()` function cannot be safely called from `getGenerators()` because the former may load assets and the latter runs in an non-game thread.
`GetAvailableFuelClasses()` also seems to be ridiculously slow, given that it calls `AFGRecipeManager::GetAllAvailableRecipes()` under the hood.
Instead, call `GetDefaultFuelClasses()` for now. It returns an array of soft class pointers, which we should NOT attempt to load since this code is still running in a non-game thread. However, we should still be able to get already-loaded classes.
> FRM_Power.cpp: Stop using `GetAvailableFuelClasses()`

- Source/FicsitRemoteMonitoring/Private/FRM_Production.cpp
- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
- setSwitches was called in /getAll endpoint
- ClassName in getSinkList was wrong (was always BlueprintGeneratedClass)
> fix: ClassName in getSinkList, remove setSwitches from getAll

- Source/FicsitRemoteMonitoring/Private/FRM_Factory.cpp
it's no longer `Desc_Crystal`, every name now has the `_C` suffix.
i am now using the UFGItemDescriptor directly
> fix: power slug name

- Source/FicsitRemoteMonitoring/Private/FRM_Production.cpp
- Source/FicsitRemoteMonitoring/Public/FicsitRemoteMonitoring.h
i replaced the usage of RecipeNames_BIE (i would remove the blueprint function later)
/getRecipes can return recipes twice if 2 schematics unlocks the same recipe, now a recipe is unique in the list
> fix: prevent duplicate recipes in getRecipes

- Source/FicsitRemoteMonitoring/Private/Endpoints/World/Session.cpp
Determines if Dedi is paused or not, client will return true as the game is required be loaded and running to call endpoint, thus will always return true, unless another mod pauses
> getSessionInfo - IsPaused

- Source/FicsitRemoteMonitoring/Private/Endpoints/Factory/Support.cpp
- Source/FicsitRemoteMonitoring/Private/Endpoints/World/Research.cpp
Example:
LogGame: Warning: FGCategory::GetCategoryName: class was nullpeter.
LogGame: Warning: FGCategory::GetCategoryName: class was nullpeter.
> Reduced log spam due to nullptr

- Source/FicsitRemoteMonitoring/Private/FicsitRemoteMonitoring.cpp
Ought to resolve, though not completely if a user connects and subscribes after uWS thread is active, but the world context is not valid.
Recommend merge after PR #233 for its CallEndpoint world context check.
> fix: StartWebSocketPushDataLoop after 1st successful WS Sub
